# Project Configuration for Predictive Maintenance

# Data settings
data:
  train_path: 'data/processed/train.csv'
  test_path: 'data/processed/test.csv'
  validation_path: 'data/processed/validation.csv'
  validation_split: 0.2
  random_state: 42
  target_column: 'Machine failure'
  features_to_exclude: ['UID', 'Product ID', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']
  categorical_features: ['Type']
  numerical_features: ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']

# Preprocessing settings
preprocessing:
  scaling: 'standard'  # Options: 'standard', 'minmax', 'robust', 'none'
  handle_missing: 'median'  # Options: 'mean', 'median', 'mode', 'drop'
  encoding: 'onehot'  # Options: 'onehot', 'label', 'target'
  feature_selection: 
    enabled: false
    method: 'rfe'  # Options: 'rfe', 'chi2', 'f_test'
    n_features: 5
  feature_engineering:
    enabled: true
    create_polynomial_features: false
    create_interaction_features: true
    create_power_features: false

# Model settings
models:
  # Random Forest settings
  random_forest:
    enabled: true
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    class_weight: 'balanced'
    
  # XGBoost settings
  xgboost:
    enabled: true
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    subsample: 0.8
    colsample_bytree: 0.8
    scale_pos_weight: 3.0  # For imbalanced classification
    
  # Neural Network settings
  neural_network:
    enabled: true
    architecture: [64, 32, 16]
    activation: 'relu'
    dropout_rate: 0.3
    batch_size: 32
    epochs: 50
    early_stopping: true
    patience: 5
    
  # Logistic Regression settings
  logistic_regression:
    enabled: true
    C: 1.0
    penalty: 'l2'
    solver: 'liblinear'
    class_weight: 'balanced'
    
  # Support Vector Machine settings
  svm:
    enabled: false  # Disabled by default due to longer training time
    C: 1.0
    kernel: 'rbf'
    gamma: 'scale'
    probability: true
    class_weight: 'balanced'

# Training settings
training:
  cross_validation: 5
  hyperparameter_tuning: 
    enabled: true
    method: 'random'  # Options: 'grid', 'random', 'bayesian'
    n_iter: 20
    cv: 3
  
# Evaluation settings
evaluation:
  metrics: ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']
  threshold: 0.5
  generate_plots: true
  feature_importance: true
  confusion_matrix: true
  
# Logging and output
logging:
  level: 'INFO'
  save_model: true
  model_path: 'models/trained_model.pkl'
  results_path: 'results/'
  
# Deployment settings
deployment:
  api_enabled: true
  api_port: 8000
  save_pipeline: true
  pipeline_path: 'models/pipeline.pkl'
  
# Real-time monitoring settings
monitoring:
  enabled: true
  drift_detection: true
  performance_tracking: true
  alert_threshold: 0.1  # Alert if performance drops by more than 10%
